# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assign3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='version',
            old_name='version_file',
            new_name='file',
        ),
    ]
