# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assign3', '0002_auto_20160317_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_summary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_msg',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
